//
// Created by Natna on 12.04.2017.
//

#ifndef UKULELEFACTORY_UKULELEFACTORYCONFIG_H_H
#define UKULELEFACTORY_UKULELEFACTORYCONFIG_H_H

#define ukuleleFactory_VERSION_MAJOR @ukuleleFactory_VERSION_MAJOR@
#define ukuleleFactory_VERSION_MINOR @ukuleleFactory_VERSION_MINOR@

#endif //UKULELEFACTORY_UKULELEFACTORYCONFIG_H_H
